client_config_backend: settings
client_config:
  client_id: 1074077007864-4hfr5174fq9414apvglfir3v7ai0n0ll.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

